import test from 'node:test';
import assert from 'node:assert/strict';
import { discoverNvFiles, seedNvSources } from '../scripts/seed-nv-sources.mjs';
const files = Array.from({length:24}, (_,i)=>({id:`id-${i+1}`,name:`NV${String(i+1).padStart(2,'0')}`,mimeType:'application/vnd.google-apps.spreadsheet'}));
test('discovers 24 active sources and skips NV15/NV16',()=>{ const r=discoverNvFiles([...files,{id:'x',name:'NV15',mimeType:'application/vnd.google-apps.spreadsheet'},{id:'y',name:'notes',mimeType:'text/plain'}]); assert.equal(r.sources.length,22); assert.ok(!r.sources.some(x=>x.nv_id==='NV15')); });
test('accepts 34 discovered files based on status, not arbitrary range',()=>{ const all=Array.from({length:34},(_,i)=>({id:`id-${i+1}`,name:`NV${String(i+1).padStart(2,'0')}`,mimeType:'application/vnd.google-apps.spreadsheet'})); const r=discoverNvFiles(all); assert.equal(r.sources.length,32); assert.deepEqual(r.skipped.filter(x=>x.reason==='inactive-config').map(x=>x.nvId),['NV15','NV16']); });
test('honours authoritative inactive config and archive status',()=>{ const r=discoverNvFiles([{id:'a',name:'NV01',mimeType:'application/vnd.google-apps.spreadsheet',status:'retired'},{id:'b',name:'NV02 archived',mimeType:'application/vnd.google-apps.spreadsheet'}],{configSources:[{nv_id:'NV02',active:false}]}); assert.equal(r.sources.length,0); assert.equal(r.skipped[0].reason,'inactive-status'); assert.equal(r.skipped[1].reason,'inactive-config'); });
test('fails closed on zero discovery',async()=>{ await assert.rejects(()=>seedNvSources({api:{listFolder:async()=>[]},db:{query:async()=>{}},folderId:'folder'}),/expected at least 1; got 0/); });
test('seed is idempotent and transactional',async()=>{let calls=[]; const db={query:async(sql,args)=>{calls.push([sql,args]);}}; const r=await seedNvSources({api:{listFolder:async()=>files},db,folderId:'folder'}); assert.equal(r.sources.length,22); assert.equal(calls[0][0],'begin'); assert.equal(calls.at(-1)[0],'commit'); assert.equal(calls.filter(x=>x[0].startsWith('insert into')).length,22);});
