import test from 'node:test';
import assert from 'node:assert/strict';
import { discoverNvFiles, seedNvSources } from '../scripts/seed-nv-sources.mjs';
const files = Array.from({length:24}, (_,i)=>({id:`id-${i+1}`,name:`NV${String(i+1).padStart(2,'0')}`,mimeType:'application/vnd.google-apps.spreadsheet'}));
test('discovers every NV without hard-coded IDs',()=>{ const r=discoverNvFiles([...files,{id:'y',name:'notes',mimeType:'text/plain'}]); assert.equal(r.sources.length,24); assert.ok(r.sources.some(x=>x.nv_id==='NV15')); });
test('accepts 34 discovered files without an arbitrary range',()=>{ const all=Array.from({length:34},(_,i)=>({id:`id-${i+1}`,name:`NV${String(i+1).padStart(2,'0')}`,mimeType:'application/vnd.google-apps.spreadsheet'})); const r=discoverNvFiles(all); assert.equal(r.sources.length,34); });
test('honours authoritative inactive status while blank status is active',()=>{ const r=discoverNvFiles([{id:'a',name:'NV01',mimeType:'application/vnd.google-apps.spreadsheet'},{id:'b',name:'NV02',mimeType:'application/vnd.google-apps.spreadsheet'}],{configSources:[{nv_id:'NV01',status:'inactive'},{nv_id:'NV02',status:''}]}); assert.equal(r.sources.length,1); assert.equal(r.sources[0].nv_id,'NV02'); assert.equal(r.skipped[0].reason,'inactive-config'); });
test('fails closed on zero discovery',async()=>{ await assert.rejects(()=>seedNvSources({api:{listFolder:async()=>[]},db:{query:async()=>{}},folderId:'folder'}),/expected at least 1; got 0/); });
test('seed is idempotent and transactional',async()=>{let calls=[]; const db={query:async(sql,args)=>{calls.push([sql,args]);return {rows:[]};}}; const r=await seedNvSources({api:{listFolder:async()=>files},db,folderId:'folder'}); assert.equal(r.sources.length,24); assert.match(calls[0][0],/select nv_id,status,active/); assert.equal(calls[1][0],'begin'); assert.equal(calls.at(-1)[0],'commit'); assert.equal(calls.filter(x=>x[0].startsWith('insert into')).length,24);});
