create table if not exists posts_raw_sheet (
  id uuid primary key default gen_random_uuid(),
  row_key text unique not null,
  source_file_id text,
  source_row integer,
  posted_date date,
  raw_posted_date text,
  posted_date_parse_ok boolean not null default true,
  brand_text_raw text,
  channel_name text,
  post_url text,
  owner_name text,
  is_exclusive boolean default false,
  viral_label text,
  realtime_view integer default 0,
  realtime_like integer default 0,
  realtime_comment integer default 0,
  realtime_save integer default 0,
  realtime_share integer default 0,
  snapshot_view integer default 0,
  snapshot_like integer default 0,
  snapshot_comment integer default 0,
  snapshot_save integer default 0,
  snapshot_share integer default 0,
  engagement_rate numeric default 0,
  status text,
  bonus_amount numeric default 0,
  show_channel text,
  viral_confirm_date date,
  source_hash text,
  raw_values jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists posts_raw_sheet_date_idx on posts_raw_sheet(posted_date);
create table if not exists post_brands_sheet (
  id uuid primary key default gen_random_uuid(),
  raw_sheet_row_key text not null,
  brand_name text not null,
  source_brand_text text,
  posted_date date,
  channel_name text,
  owner_name text,
  post_url text,
  realtime_view integer default 0,
  realtime_like integer default 0,
  realtime_comment integer default 0,
  realtime_save integer default 0,
  realtime_share integer default 0,
  viral_label text,
  bonus_amount numeric default 0,
  unique(raw_sheet_row_key, brand_name)
);
create index if not exists post_brands_sheet_brand_idx on post_brands_sheet(brand_name);
create index if not exists post_brands_sheet_date_idx on post_brands_sheet(posted_date);
